# Generated by Django 5.2.12 on 2026-04-29 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcurve",
            name="test",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curve",
                to="api.test",
            ),
        ),
    ]
