# Generated by Django 5.2.12 on 2026-05-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_testcurve_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.IntegerField()),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="audit_timestamp_idx"),
                    models.Index(fields=["user", "-timestamp"], name="audit_user_timestamp_idx"),
                    models.Index(fields=["path", "-timestamp"], name="audit_path_timestamp_idx"),
                ],
            },
        ),
    ]
