# Generated by Django 5.2.12 on 2026-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="bolt",
            name="client_product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External product ID from supplier, combined with supplier_id for uniqueness",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="client_test_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External test ID from supplier, combined with supplier_id for uniqueness",
                max_length=255,
                null=True,
            ),
        ),
    ]
