# Generated by Django 5.2.12 on 2026-05-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_bolt_client_product_id_test_client_test_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bolt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="bolts", to="api.supplier"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="bolt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tests", to="api.bolt"
            ),
        ),
    ]
